// <auto-generated />
namespace SimSo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class add_sim_client : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_sim_client));
        
        string IMigrationMetadata.Id
        {
            get { return "201505210700573_add_sim_client"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
